"""initial schema

Revision ID: 783417c3a52a
Revises: 
Create Date: 2026-06-22 17:54:17.112693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '783417c3a52a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_anonymous_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('situations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('situation_type', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('just_started', 'in_it', 'turning_point', 'resolved', name='stage'), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('outcome_text', sa.Text(), nullable=True),
    sa.Column('embedding_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_situations_situation_type'), 'situations', ['situation_type'], unique=False)
    op.create_index(op.f('ix_situations_stage'), 'situations', ['stage'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('situation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['situation_id'], ['situations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'situation_id', name='uq_follow_once')
    )
    op.create_table('reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('situation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('been_there', 'rooting_for_you', name='reactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['situation_id'], ['situations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('situation_id', 'user_id', 'type', name='uq_reaction_once')
    )
    op.create_table('situation_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('situation_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('just_started', 'in_it', 'turning_point', 'resolved', name='stage'), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['situation_id'], ['situations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('situation_updates')
    op.drop_table('reactions')
    op.drop_table('follows')
    op.drop_index(op.f('ix_situations_stage'), table_name='situations')
    op.drop_index(op.f('ix_situations_situation_type'), table_name='situations')
    op.drop_table('situations')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
